### ISSUE TITLE
cannot import name 'entsToTxt' from 'anki.utils' in 2.1.50

### ISSUE THREAD

**Issue by homocomputeris** [Ajatt-Tools/mergenotes#6]
I've tried the git version of Anki and got the following error. I wonder if it will affect mergenotes when x.50 is released.

Anki 2.1.50 (627f9106)⁩
Python 3.9.9 Qt 5.15.2 PyQt 5.15.6
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/aqt/addons.py", line 239, in loadAddons
    __import__(addon.dir_name)
  File "/home/nik/.local/share/Anki2/addons21/1425504015/__init__.py", line 4, in <module>
    from . import merge_duplicates, merge_notes, settings_dialog, duplicate_notes
  File "/home/nik/.local/share/Anki2/addons21/1425504015/merge_duplicates.py", line 17, in <module>
    from .merge_notes import MergeNotes
  File "/home/nik/.local/share/Anki2/addons21/1425504015/merge_notes.py", line 11, in <module>
    from anki.utils import entsToTxt
ImportError: cannot import name 'entsToTxt' from 'anki.utils' (/usr/lib/python3.9/site-packages/anki/utils.py)
```

**Comment by tatsumoto-ren** [comment]
Can't say anything about 2.1.50 yet. I'm going to try it.

Update: I can't try it right now. Apparently the beta hasn't been released on PyPI yet. https://pypi.org/project/aqt/

**Comment by homocomputeris** [comment]
Sure, no problems, I fully understand it's a dev build I'm using. I though it might be better to report sooner than later.

**Comment by tatsumoto-ren** [comment]
Anki devs are working hard every day to make the program worse and break as many add-ons as possible. Ultimately, Anki needs to be completely replaced because the current devs are doing everything they can to alienate add-on developers.

It seems this time they simply removed the function, and that's why you are experiencing this error.

https://github.com/ankitects/anki/commit/0bb273a0ed90d7548052d5c9b10467ea577fc1e0

**Comment by dae** [comment]
That is not really fair. This change was not made on a whim; it was to address a security report. And at the time, I searched through all add-ons and found none that were using entsToTxt. You appear to have only added it to your codebase a week ago, well after this change was made. Since it is not used by Anki anymore, I recommend you just include it in your add-on.

I get that it's frustrating when things break, but please bear in mind that add-ons are so tightly coupled to Anki's codebase that it's almost impossible to improve the codebase and remain compatible with everything. In the last two years there have been a fair few breakages, but the codebase is in much better shape now than it was back then, and that means both a more maintainable Anki, and an easier time for new add-on developers.

**Comment by tatsumoto-ren** [comment]
Thank you for the response. Looks like `stripHTMLMedia` is still present in the code base. I'm going to use the function for this add-on instead. Hope it doesn't disappear in the future like the others 🥲.

**Comment by homocomputeris** [comment]
Is it possible to have an equivalent function in the addon itself instead of relying on the function provided by Anki, as dae suggests?
Building on top of more general backend functions implemented in the faster Rust seems quite reasonable.

**Comment by tatsumoto-ren** [comment]
It's possible to just copy `entsToTxt` from the old Anki code to this add-on, but it's not really that necessary. `stripHTMLMedia` does something similar.
